# Generated by Django 5.2.16 on 2026-08-01 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('villas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('checkin', models.DateField(db_index=True)),
                ('checkout', models.DateField(db_index=True)),
                ('guests_count', models.PositiveSmallIntegerField()),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('deposit_paid_online', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('remaining_payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card_on_arrival', 'کارت در محل'), ('online_later', 'آنلاین بعدی')], default='card_on_arrival', max_length=24)),
                ('cancellation_policy_applied', models.JSONField(blank=True, default=dict)),
                ('refund_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending_owner', 'در انتظار تأیید'), ('confirmed', 'تأییدشده'), ('cancelled', 'لغوشده'), ('completed', 'تکمیل\u200cشده')], db_index=True, default='pending_owner', max_length=24)),
                ('guest_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='villas.villa')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('zibal', 'زیبال'), ('idpay', 'آی\u200cدی\u200cپی')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت\u200cشده'), ('partially_paid', 'پرداخت جزئی'), ('refunded', 'بازگشت\u200cداده\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=20)),
                ('authority', models.CharField(blank=True, max_length=120)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['villa', 'checkin', 'checkout'], name='bookings_bo_villa_i_c85369_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', 'status'], name='bookings_bo_guest_i_261eaf_idx'),
        ),
    ]
