# Generated by Django 5.2.16 on 2026-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_due_now',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_plan',
            field=models.CharField(choices=[('deposit', 'بیعانه'), ('full', 'پرداخت کامل')], default='deposit', max_length=12),
        ),
    ]
