# Generated by Django 5.2.16 on 2026-08-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_amount_due_now_booking_payment_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'در انتظار بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('refunded', 'وجه بازگردانده شد')], db_index=True, default='requested', max_length=16)),
                ('admin_note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_requests', to='bookings.booking')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
