# Generated by Django 5.2.16 on 2026-08-02 08:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_supportticket'),
        ('villas', '0002_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده')], db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='bookings.booking')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='villas.villa')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['villa', 'status', 'created_at'], name='bookings_re_villa_i_2692c6_idx')],
            },
        ),
    ]
