# Generated by Django 5.2.16 on 2026-08-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrequest',
            name='estimated_refund_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='refund_percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
