# Generated by Django 5.2.16 on 2026-08-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_cancellationrequest_estimated_refund_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('manual', 'ثبت دستی'), ('zarinpal', 'زرین\u200cپال'), ('zibal', 'زیبال'), ('idpay', 'آی\u200cدی\u200cپی')], max_length=16),
        ),
    ]
