# Generated by Django 5.2.16 on 2026-08-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_payment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_owner', 'در انتظار تأیید'), ('confirmed', 'تأییدشده'), ('cancelled', 'لغوشده'), ('completed', 'تکمیل\u200cشده'), ('expired', 'منقضی\u200cشده')], db_index=True, default='pending_owner', max_length=24),
        ),
    ]
