# Generated by Django 5.2.16 on 2026-08-02 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_expires_at_alter_booking_status'),
        ('marketplace', '0003_serviceoffer_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='services_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='booking',
            name='stay_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('requested', 'در انتظار هماهنگی'), ('confirmed', 'تأیید شده'), ('unavailable', 'ناموجود'), ('completed', 'انجام شده')], default='requested', max_length=16)),
                ('admin_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_items', to='bookings.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='marketplace.serviceoffer')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'service'), name='unique_booking_service')],
            },
        ),
    ]
