# Generated by Django 5.2.16 on 2026-08-08 08:29

import apps.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_payment_attempt_number_payment_proof_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, storage=apps.bookings.models.PaymentProofStorage(), upload_to='payment-proofs/%Y/%m/'),
        ),
    ]
