# Generated by Django 5.2.16 on 2026-08-02 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'بایگانی')], db_index=True, default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('category', models.CharField(default='راهنمای سفر', max_length=80)),
                ('author_name', models.CharField(default='تحریریه ویلاوان', max_length=100)),
                ('cover_image', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'بایگانی')], db_index=True, default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('specialty', models.CharField(max_length=140)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('services', models.JSONField(blank=True, default=list)),
                ('cover_image', models.CharField(max_length=500)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-verified', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'بایگانی')], db_index=True, default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('property_type', models.CharField(choices=[('villa', 'ویلا'), ('land', 'زمین'), ('apartment', 'آپارتمان')], default='villa', max_length=16)),
                ('price', models.DecimalField(decimal_places=0, max_digits=16)),
                ('area_m2', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('features', models.JSONField(blank=True, default=list)),
                ('cover_image', models.CharField(max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('real_estate', 'مشاوره ملک'), ('contractor', 'درخواست پیمانکار')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شد'), ('closed', 'بسته')], db_index=True, default='new', max_length=12)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='marketplace.contractor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_inquiries', to=settings.AUTH_USER_MODEL)),
                ('real_estate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='marketplace.realestatelisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
