# Generated by Django 5.2.16 on 2026-08-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'بایگانی')], db_index=True, default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('price_note', models.CharField(max_length=160)),
                ('cover_image', models.CharField(max_length=500)),
                ('features', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='kind',
            field=models.CharField(choices=[('real_estate', 'مشاوره ملک'), ('contractor', 'درخواست پیمانکار'), ('service', 'خدمات سفر')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='marketplace.serviceoffer'),
        ),
    ]
