# Generated by Django 5.2.16 on 2026-08-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_serviceoffer_alter_inquiry_kind_inquiry_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
    ]
