# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_serviceoffer_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="assigned_contractor",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assigned_inquiries", to="marketplace.contractor"),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="follow_up_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="status",
            field=models.CharField(choices=[("new", "جدید"), ("contacted", "تماس گرفته شد"), ("introduced", "معرفی شده"), ("closed", "بسته")], db_index=True, max_length=12, default="new"),
        ),
    ]
