# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0004_contractor_release"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractor",
            options={"ordering": ["-featured", "-verified", "name"]},
        ),
    ]
