# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0005_alter_contractor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="catalog",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
