# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("marketplace", "0006_contractor_catalog")]

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("brand_name", models.CharField(default="ویلاوان", max_length=100)),
                ("support_phone", models.CharField(blank=True, max_length=30)),
                ("support_whatsapp", models.CharField(blank=True, max_length=30)),
                ("operating_hours", models.CharField(blank=True, max_length=180)),
                ("footer_description", models.TextField(blank=True)),
                ("terms_text", models.TextField(blank=True)),
                ("privacy_text", models.TextField(blank=True)),
                ("cancellation_text", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "تنظیمات کسب‌وکار", "verbose_name_plural": "تنظیمات کسب‌وکار"},
        ),
    ]
