# Generated by Django 5.2.16 on 2026-08-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_businesssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uploaded_cover_image',
            field=models.ImageField(blank=True, upload_to='articles/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='uploaded_cover_image',
            field=models.ImageField(blank=True, upload_to='contractors/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='realestatelisting',
            name='uploaded_cover_image',
            field=models.ImageField(blank=True, upload_to='real-estate/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='uploaded_cover_image',
            field=models.ImageField(blank=True, upload_to='services/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='cover_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='realestatelisting',
            name='cover_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='cover_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
