# Generated by Django 5.2.16 on 2026-08-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_article_uploaded_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='card_transfer_bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='card_transfer_card_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='card_transfer_cardholder_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='card_transfer_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
