# Generated by Django 5.2.16 on 2026-08-09 15:40

import apps.marketplace.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def map_legacy_article_categories(apps, schema_editor):
    Article = apps.get_model("marketplace", "Article")
    Article.objects.filter(category="راهنمای سفر").update(category="guide")


def restore_legacy_article_categories(apps, schema_editor):
    Article = apps.get_model("marketplace", "Article")
    Article.objects.filter(category="guide").update(category="راهنمای سفر")


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_serviceoffer_booking_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_alt',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='article',
            name='cta_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='article',
            name='cta_url',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('guide', 'راهنمای سفر'), ('stay', 'اقامت و ویلا'), ('design', 'معماری و بازسازی'), ('property', 'ملک و سرمایه\u200cگذاری'), ('local', 'تجربه و خدمات محلی')], db_index=True, default='guide', max_length=24),
        ),
        migrations.AlterField(
            model_name='article',
            name='uploaded_cover_image',
            field=models.ImageField(blank=True, upload_to='articles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), apps.marketplace.models.validate_article_upload]),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(validators=[apps.marketplace.models.validate_article_image_key])),
                ('image', models.ImageField(upload_to='articles/inline/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), apps.marketplace.models.validate_article_upload])),
                ('alt_text', models.CharField(max_length=180)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_images', to='marketplace.article')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('article', 'key'), name='unique_article_image_key')],
            },
        ),
        migrations.RunPython(map_legacy_article_categories, restore_legacy_article_categories),
    ]
