# Generated by Django 5.2.16 on 2026-08-09 15:59

import apps.marketplace.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_normalize_article_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to='articles/inline/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), apps.marketplace.models.validate_article_upload], width_field='width'),
        ),
    ]
