from django.core.management.base import BaseCommand

from apps.marketplace.models import ServiceOffer


SERVICES = (
    {
        "slug": "private-chef",
        "title": "آشپز خصوصی در ویلا",
        "category": "پذیرایی خصوصی",
        "short_description": "یک وعده اختصاصی با منوی هماهنگ‌شده، آماده و سرو‌شده در ویلای شما.",
        "description": "آشپز محلی پیش از اقامت درباره تعداد مهمانان، سبک منو و حساسیت‌های غذایی با شما هماهنگ می‌کند. مواد اولیه، آماده‌سازی و سرو وعده در ویلا انجام می‌شود و جزئیات نهایی در صف عملیات تیم ویلاوان قرار می‌گیرد.",
        "price_note": "قیمت پایه برای هر مهمان؛ منوی نهایی پیش از تأیید هماهنگ می‌شود.",
        "base_price": 1_450_000,
        "cover_image": "/images/villas/experience.jpg",
        "features": ["منوی هماهنگ‌شده", "آشپزی در محل", "امکان ثبت حساسیت غذایی", "پیگیری توسط کانسیرج"],
        "inclusions": ["هماهنگی منو", "مواد اولیه منوی توافق‌شده", "آماده‌سازی و سرو در ویلا", "جمع‌آوری فضای کار آشپز"],
        "exclusions": ["نوشیدنی‌های خارج از منو", "تجهیزات خاص پذیرایی", "دکور مراسم"],
        "preparation_notes": "تعداد دقیق مهمانان و هرگونه حساسیت غذایی را در یادداشت خدمت بنویسید. دسترسی آشپزخانه ویلا باید در زمان هماهنگ‌شده ممکن باشد.",
        "cancellation_text": "لغو یا تغییر منو پس از خرید مواد اولیه ممکن است شامل هزینه باشد. نتیجه نهایی پیش از تأیید خدمت به مهمان اعلام می‌شود.",
        "fulfillment_mode": "both",
        "pricing_model": "per_guest",
        "unit_label": "مهمان",
        "minimum_quantity": 1,
        "maximum_quantity": 1,
        "minimum_lead_hours": 24,
        "default_daily_capacity": 2,
        "schedule_type": "stay_date",
        "featured": True,
        "sort_order": 10,
    },
    {
        "slug": "local-breakfast",
        "title": "صبحانه محلی مازندران",
        "category": "پذیرایی",
        "short_description": "سبد صبحانه تازه محلی، تحویل‌شده در ویلای شما در صبح انتخابی.",
        "description": "صبحانه‌ای ساده و محلی با اقلامی که پیش از اقامت براساس تعداد مهمانان آماده می‌شود. موجودی و جزئیات بسته به فصل و تأمین روز تغییر می‌کند.",
        "price_note": "قیمت برای هر مهمان",
        "base_price": 520_000,
        "cover_image": "/images/villas/villa-02.jpg",
        "features": ["اقلام تازه روز", "تحویل در ویلا", "انتخاب روز اقامت"],
        "inclusions": ["نان تازه", "پنیر و کره", "مربا یا عسل", "چای محلی"],
        "exclusions": ["سرویس میزبان", "منوی گرم سفارشی"],
        "preparation_notes": "حساسیت غذایی یا رژیم خاص را هنگام انتخاب خدمت ثبت کنید.",
        "cancellation_text": "تغییر تعداد تا پیش از تأمین نهایی مواد اولیه قابل بررسی است.",
        "fulfillment_mode": "bookable",
        "pricing_model": "per_guest",
        "unit_label": "مهمان",
        "minimum_quantity": 1,
        "maximum_quantity": 1,
        "minimum_lead_hours": 18,
        "default_daily_capacity": 6,
        "schedule_type": "stay_date",
        "featured": False,
        "sort_order": 20,
    },
    {
        "slug": "arrival-welcome-basket",
        "title": "سبد خوش‌آمدگویی ویلا",
        "category": "آماده‌سازی ورود",
        "short_description": "میوه، نوشیدنی و خوراکی محلی که پیش از ورود در ویلا چیده می‌شود.",
        "description": "سبد خوش‌آمدگویی برای ورود آرام‌تر مهمانان آماده می‌شود. می‌توانید چند سبد انتخاب کنید و درخواست مناسبتی را در یادداشت بنویسید.",
        "price_note": "قیمت هر سبد",
        "base_price": 1_250_000,
        "cover_image": "/images/villas/villa-06.jpg",
        "features": ["آماده پیش از ورود", "محصولات فصلی", "امکان ثبت پیام مناسبتی"],
        "inclusions": ["میوه فصل", "نوشیدنی غیرالکلی", "خوراکی محلی", "چیدمان ساده"],
        "exclusions": ["گل‌آرایی", "دکور مراسم"],
        "preparation_notes": "متن کارت یا مناسبت را در یادداشت خدمت وارد کنید.",
        "cancellation_text": "پس از آماده‌سازی سبد، لغو ممکن است شامل هزینه اقلام تهیه‌شده باشد.",
        "fulfillment_mode": "bookable",
        "pricing_model": "per_unit",
        "unit_label": "سبد",
        "minimum_quantity": 1,
        "maximum_quantity": 4,
        "minimum_lead_hours": 12,
        "default_daily_capacity": 10,
        "schedule_type": "checkin",
        "featured": False,
        "sort_order": 30,
    },
    {
        "slug": "mid-stay-housekeeping",
        "title": "نظافت میان‌اقامت",
        "category": "آسایش اقامت",
        "short_description": "مرتب‌سازی و نظافت سبک ویلا برای اقامت‌های طولانی‌تر.",
        "description": "تیم خدمات در روز انتخابی برای نظافت فضاهای عمومی، سرویس‌ها و جمع‌آوری پسماند مراجعه می‌کند. این خدمت نظافت سبک میان‌اقامت است و جایگزین نظافت عمیق یا رسیدگی به خسارت نیست.",
        "price_note": "قیمت هر نوبت نظافت",
        "base_price": 1_900_000,
        "cover_image": "/images/villas/villa-05.jpg",
        "features": ["انتخاب روز اقامت", "هماهنگی ساعت ورود", "نظافت سبک فضاهای اصلی"],
        "inclusions": ["مرتب‌سازی فضای عمومی", "نظافت سرویس‌ها", "جمع‌آوری پسماند", "تعویض حوله در صورت موجودی ویلا"],
        "exclusions": ["شست‌وشوی لباس", "نظافت پس از مهمانی", "رسیدگی به خسارت"],
        "preparation_notes": "زمانی را انتخاب کنید که دسترسی تیم به ویلا ممکن باشد. اشیای شخصی و ارزشمند را پیش از مراجعه جمع‌آوری کنید.",
        "cancellation_text": "تغییر زمان تا پیش از اعزام تیم قابل بررسی است.",
        "fulfillment_mode": "bookable",
        "pricing_model": "per_unit",
        "unit_label": "نوبت",
        "minimum_quantity": 1,
        "maximum_quantity": 3,
        "minimum_lead_hours": 12,
        "default_daily_capacity": 5,
        "schedule_type": "stay_date",
        "featured": False,
        "sort_order": 40,
    },
    {
        "slug": "private-transfer",
        "title": "ترانسفر خصوصی تا ویلا",
        "category": "رفت‌وآمد",
        "short_description": "درخواست خودروی دربستی از مبدأ هماهنگ‌شده تا اقامتگاه.",
        "description": "پس از ثبت درخواست، مبدأ، تعداد مسافر، میزان بار و نوع خودرو توسط کانسیرج بررسی می‌شود. به‌دلیل تغییر فاصله و مسیر، قیمت نهایی پس از هماهنگی اعلام خواهد شد.",
        "price_note": "قیمت پس از مشخص‌شدن مبدأ و نوع خودرو",
        "base_price": 0,
        "cover_image": "/images/villas/villa-07.jpg",
        "features": ["هماهنگی مبدأ", "انتخاب نوع خودرو", "پیگیری تا زمان ورود"],
        "inclusions": ["بررسی مسیر", "معرفی راننده", "پیگیری زمان حرکت"],
        "exclusions": ["توقف‌های خارج از مسیر", "هزینه پارکینگ یا ورودی", "صندلی کودک مگر با هماهنگی"],
        "preparation_notes": "مبدأ، ساعت حرکت، تعداد مسافر و حجم تقریبی بار را در درخواست بنویسید.",
        "cancellation_text": "شرایط لغو پس از معرفی راننده و اعلام قیمت نهایی مشخص می‌شود.",
        "fulfillment_mode": "inquiry_only",
        "pricing_model": "fixed",
        "unit_label": "سفر",
        "minimum_quantity": 1,
        "maximum_quantity": 1,
        "minimum_lead_hours": 12,
        "default_daily_capacity": 4,
        "schedule_type": "checkin",
        "featured": False,
        "sort_order": 50,
    },
    {
        "slug": "villa-photography",
        "title": "عکاسی خصوصی سفر",
        "category": "تجربه",
        "short_description": "جلسه عکاسی سبک زندگی در ویلا یا طبیعت نزدیک اقامتگاه.",
        "description": "پس از ثبت درخواست، سبک عکاسی، لوکیشن و زمان مناسب با مهمان هماهنگ می‌شود. این خدمت به‌دلیل وابستگی به عکاس و شرایط آب‌وهوا به‌صورت درخواست کانسیرج ارائه می‌شود.",
        "price_note": "برآورد پس از مشخص‌شدن زمان و سبک عکاسی",
        "base_price": 4_500_000,
        "cover_image": "/images/villas/villa-08.jpg",
        "features": ["هماهنگی لوکیشن", "عکاس محلی", "انتخاب تصاویر نهایی"],
        "inclusions": ["جلسه برنامه‌ریزی کوتاه", "عکاسی در بازه توافق‌شده", "تحویل فایل‌های منتخب"],
        "exclusions": ["چاپ آلبوم", "گریم و استایل", "ورودی لوکیشن‌های خصوصی"],
        "preparation_notes": "تعداد نفرات و سبک مدنظر را در درخواست توضیح دهید.",
        "cancellation_text": "شرایط تغییر زمان پس از معرفی عکاس و پیش از تأیید نهایی اعلام می‌شود.",
        "fulfillment_mode": "inquiry_only",
        "pricing_model": "fixed",
        "unit_label": "جلسه",
        "minimum_quantity": 1,
        "maximum_quantity": 1,
        "minimum_lead_hours": 24,
        "default_daily_capacity": 2,
        "schedule_type": "stay_date",
        "featured": False,
        "sort_order": 60,
    },
)

LEGACY_LOCAL_FIXTURES = ("forest-photography", "private-spa", "mazandaran-day-tour")


class Command(BaseCommand):
    help = "Creates an idempotent local service catalogue. Records stay draft unless --publish is explicitly supplied."

    def add_arguments(self, parser):
        parser.add_argument("--publish", action="store_true", help="Publish the local preview catalogue intentionally.")

    def handle(self, *args, **options):
        status = ServiceOffer.Status.PUBLISHED if options["publish"] else ServiceOffer.Status.DRAFT
        ServiceOffer.objects.filter(slug__in=LEGACY_LOCAL_FIXTURES).update(status=ServiceOffer.Status.DRAFT)
        for payload in SERVICES:
            ServiceOffer.objects.update_or_create(slug=payload["slug"], defaults={**payload, "status": status})
        self.stdout.write(self.style.SUCCESS(f"Service catalogue created as {status}: {len(SERVICES)} records."))
