import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { InnerHeader } from "../../components/InnerHeader";
import { PublicFooter } from "../../components/PublicFooter";
import { VillaOneApiError, type JournalArticle, fetchArticle, formatPersianDate } from "../../lib/api";
import ArticleReader from "./ArticleReader";
import styles from "../Journal.module.css";

type ArticlePageProps = { params: Promise<{ slug: string }> };

async function getArticle(slug: string) {
  try {
    return await fetchArticle(slug);
  } catch (error) {
    if (error instanceof VillaOneApiError && error.status === 404) notFound();
    throw error;
  }
}

export async function generateMetadata({ params }: ArticlePageProps): Promise<Metadata> {
  const { slug } = await params;
  const article = await getArticle(slug);
  if (!article) return { title: "مجله ویلاوان" };
  const siteUrl = process.env.NEXT_PUBLIC_VILLAONE_SITE_URL || "http://localhost:3001";
  const canonical = `${siteUrl}/journal/${article.slug}`;
  return {
    title: `${article.title} | مجله ویلاوان`,
    description: article.excerpt,
    alternates: { canonical },
    openGraph: {
      title: article.title,
      description: article.excerpt,
      url: canonical,
      type: "article",
      locale: "fa_IR",
      publishedTime: article.published_at || undefined,
      modifiedTime: article.updated_at || undefined,
      authors: [article.author_name],
      images: article.cover_image ? [{ url: article.cover_image, alt: article.cover_alt || article.title }] : undefined,
    },
    twitter: { card: "summary_large_image", title: article.title, description: article.excerpt, images: article.cover_image ? [article.cover_image] : undefined },
  };
}

function getHeadings(bodyHtml: string | null | undefined) {
  if (!bodyHtml) return [];
  const headings: { id: string; label: string; level: number }[] = [];
  const regex = /<h([2-4])[^>]*id="([^"]+)"[^>]*>(.*?)<\/h\1>/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(bodyHtml))) {
    headings.push({ id: match[2], label: match[3].replace(/<[^>]+>/g, ""), level: Number(match[1]) });
  }
  return headings;
}

function ArticleCover({ article }: { article: JournalArticle }) {
  return article.cover_image ? <img className="article-cover" src={article.cover_image} alt={article.cover_alt || article.title} /> : <div className="article-cover article-image-fallback"><span>ویلاوان</span></div>;
}

export default async function ArticlePage({ params }: ArticlePageProps) {
  const { slug } = await params;
  const article = await getArticle(slug);
  if (!article) return <main dir="rtl" className={`${styles.articlePage} inner-page article-page`}><InnerHeader /><section className="journal-state section-shell"><strong>مقاله موقتاً در دسترس نیست.</strong><p>مقاله‌های منتشرشده پس از آماده‌سازی از اینجا در دسترس هستند.</p><a href="/journal">بازگشت به مجله</a></section><PublicFooter /></main>;

  const siteUrl = process.env.NEXT_PUBLIC_VILLAONE_SITE_URL || "http://localhost:3001";
  const headings = getHeadings(article.body_html);
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: article.title,
    description: article.excerpt,
    datePublished: article.published_at,
    dateModified: article.updated_at || article.published_at,
    author: { "@type": "Organization", name: article.author_name },
    publisher: { "@type": "Organization", name: "VillaOne" },
    mainEntityOfPage: `${siteUrl}/journal/${article.slug}`,
    image: article.cover_image ? [article.cover_image] : undefined,
    inLanguage: "fa-IR",
  };
  const jsonLdString = JSON.stringify(jsonLd).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026");

  return (
    <main dir="rtl" className={`${styles.articlePage} inner-page article-page`}>
      <InnerHeader />
      <article>
        <header className="article-header">
          <span className="journal-category">{article.category}</span>
          <h1>{article.title}</h1>
          <p className="article-excerpt">{article.excerpt}</p>
          <div className="article-meta"><span>{article.author_name}</span>{article.published_at && <time dateTime={article.published_at}>{formatPersianDate(article.published_at)}</time>}{article.reading_time_minutes && <span>{article.reading_time_minutes} دقیقه مطالعه</span>}</div>
        </header>
        <ArticleCover article={article} />
        <ArticleReader title={article.title}>
          <div className={headings.length > 0 ? "article-reading-layout has-toc" : "article-reading-layout"}>
            {headings.length > 0 && <aside className="article-toc" aria-label="فهرست مقاله"><strong>در این مقاله</strong><ol>{headings.map((heading) => <li key={heading.id} className={`level-${heading.level}`}><a href={`#${heading.id}`}>{heading.label}</a></li>)}</ol></aside>}
            {/* body_html is generated by Django's strict allowlisted renderer; raw Markdown never reaches the DOM. */}
            <div className="article-body" dangerouslySetInnerHTML={{ __html: article.body_html || "" }} />
          </div>
        </ArticleReader>
        {article.cta && <Link className="article-cta" href={article.cta.url}>{article.cta.label}<span>←</span></Link>}
        {article.related_articles && article.related_articles.length > 0 && <section className="article-related" aria-labelledby="related-articles"><div className="section-heading"><p className="eyebrow dark"><span /> ادامه بخوانید</p><h2 id="related-articles">روایت‌های مرتبط</h2></div><div className="article-related-grid">{article.related_articles.map((related) => <Link key={related.slug} href={`/journal/${related.slug}`}><div className="article-related-image">{related.cover_image ? <img src={related.cover_image} alt={related.title} /> : <span>ویلاوان</span>}</div><span>{related.category}</span><h3>{related.title}</h3></Link>)}</div></section>}
        <footer className="article-footer"><Link href="/journal">← بازگشت به مجله</Link><Link href="/villas">کشف ویلاهای ویلاوان <span>↗</span></Link></footer>
      </article>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLdString }} />
      <PublicFooter />
    </main>
  );
}
