# Generated by Django 5.2.16 on 2026-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_booking_sms_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchallenge',
            name='request_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
