# Generated by Django 5.2.16 on 2026-08-01 09:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name_plural': 'امکانات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('region', models.CharField(default='مازندران', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('address', models.TextField(blank=True, help_text='فقط پس از رزرو تأییدشده نمایش داده می\u200cشود.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_radius_meters', models.PositiveIntegerField(default=500)),
                ('setting_tags', models.JSONField(blank=True, default=list)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('beds', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('price_weekday', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_weekend', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_holiday', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_percentage', models.PositiveSmallIntegerField(default=30)),
                ('cancellation_policy', models.JSONField(blank=True, default=dict)),
                ('is_instant_bookable', models.BooleanField(default=False)),
                ('requires_id_verification', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار بررسی'), ('published', 'منتشرشده'), ('suspended', 'تعلیق\u200cشده')], db_index=True, default='draft', max_length=24)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='villas', to='villas.amenity')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villas', to='villas.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_villas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='villas.villa')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'آزاد'), ('blocked', 'مسدود'), ('booked', 'رزروشده')], default='open', max_length=12)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='villas.villa')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='VillaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=700)),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='villas.villa')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='villa',
            index=models.Index(fields=['city', 'status'], name='villas_vill_city_id_eb60d9_idx'),
        ),
        migrations.AddIndex(
            model_name='villa',
            index=models.Index(fields=['status', 'featured'], name='villas_vill_status_fbc264_idx'),
        ),
        migrations.AddConstraint(
            model_name='priceoverride',
            constraint=models.UniqueConstraint(fields=('villa', 'date'), name='unique_villa_price_date'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('villa', 'date'), name='unique_villa_availability_date'),
        ),
    ]
