# Generated by Django 5.2.16 on 2026-08-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='villaimage',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='villas/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='villaimage',
            name='url',
            field=models.URLField(blank=True, default='', max_length=700),
        ),
    ]
